### ISSUE TITLE
As a user, I want to be able to sign up for the app

### ISSUE THREAD

**Issue by valfink** [valfink/banana-rescue#1]
"Hi! I don't know what this App is all about, but I really want to sign up for it!"

- backend
  - Add Spring Security, setup `SecurityFilterChain`
  - GET endpoint `/api/csrf` to retrieve CSRF token
  - POST endpoint `/api/users/signup`
  - `User` model
- frontend
  - signup page
  - route: `/signup`
  - navigation link
- unit and integration tests

**Comment by gadmel** [comment]
Love your project plan and your agile board. Gonna make myself something similar!
